### ISSUE TITLE
Hi, request to add a feature

### ISSUE THREAD

**Issue by krafairus** [Dvlv/BoxBuddyRS#10]
I wanted to make a request to add a feature, For now, when you click "add menu" an application listed in the pop-up window that shows the apps installed in a distrobox container is added to the desktop in the path:

/home/$user$/.local/share/applications

The problem is that the .desktop comes without the icon, what you could do is a symbolic link to a folder located in the boxbuddyrs files folder or copy the icons to a folder with any name to the boxbuddyrs folder, I hope you can solve that, good luck.

![Screenshot_20240111_123734](https://github.com/Dvlv/BoxBuddyRS/assets/64279814/3efff362-c5b2-46d7-bee4-c68d49443065)

**Comment by Dvlv** [comment]
Hello, this is functionality in Distrobox itself. 
The icon should be exported by `distrobox-export`, and if you close and re-open the View Applications modal, you should then see the icon.
