### ISSUE TITLE
BUG: Preferred terminal being misselected

### ISSUE THREAD

**Issue by Ian-Marcel** [Dvlv/BoxBuddyRS#107]
1. **Install method (Flatpak/Binary/Other)**
- _Flatpak_
2. **Distrobox Version**
- `1.7.2.1`
3. **Your Host OS**
- _Fedora 39 Workstation x86_64 | Gnome 45.7_

When selecting a preferred terminal and saving it, the app will actually select the terminal below the one selected by the user, see the following video

[Record.webm](https://github.com/Dvlv/BoxBuddyRS/assets/96081694/84fe5dd8-a3ad-47ed-baf8-490d36c88c53)

**Comment by Dvlv** [comment]
Thank you for the report, I have pushed a fix and will get it to flathub hopefully tonight.

**Comment by Dvlv** [comment]
2.2.8 making its way through Flathub now.

**Comment by Ian-Marcel** [comment]
I've tested 2.2.8, problem solved, thanks! :cowboy_hat_face:
