### ISSUE TITLE
Missing Assemble "hammer" button

### ISSUE THREAD

**Issue by Stef16Robbe** [Dvlv/BoxBuddyRS#108]
**Install method (Flatpak/Binary/Other)**

Flatpak! My version is reported as `2.2.8` which is also the latest as far as I've seen.

**Distrobox Version**

```shell
stef@zeno ~> distrobox --version
distrobox: 1.7.2.1
```

**Your Host OS**

`Fedora Linux 40.20240629.0 (Silverblue)`

**Describe your Issue**

The assemble distrobox button is not showing:

![image](https://github.com/Dvlv/BoxBuddyRS/assets/43065653/04c582a1-432f-420c-a201-4cbf5303ec08)

It does show when I pull and build the `master` branch:

![image](https://github.com/Dvlv/BoxBuddyRS/assets/43065653/53ef6819-008f-4f5e-a154-326697fad92e)

A reinstall did not fix the issue.

**Comment by VortexAcherontic** [comment]
This is to be expected as the flat requires additional permissions for this, see: https://dvlv.github.io/BoxBuddyRS/guide#using-distrobox-assemble

**Comment by Stef16Robbe** [comment]
Now that you've mentioned it I see it's also [in the FAQ](https://dvlv.github.io/BoxBuddyRS/faqs)... Sorry about that and thanks!

**Comment by dennis1248** [comment]
For people running in to this issue in the future;

`sudo flatpak override --filesystem=home io.github.dvlv.boxbuddyrs`
