### ISSUE TITLE
Provide a better loading indication

### ISSUE THREAD

**Issue by realitymolder** [Dvlv/BoxBuddyRS#109]
- [V ] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [ V] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [ V] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
Upon creation of a box via BoxBuddy, provide a better loading / with verbose option. At the moment my internet connection is not the best, so I'm not sure if BoxBuddy is stuck on the loading animation or it is actually downloading the container in the background. 

Edit: This issue might be bigger than what is reported here, currently im using boxbuddy for management. Creation i do only via distrobox cli due to the fact that it is broken for me

**Comment by Dvlv** [comment]
Hello

my initial plan was to stream the output of the creation where the loading spinner was. Unfortunately I couldn't get it to work. I also couldn't get VTE to compile either, so I had to give up on the idea and just show a spinner.

I would definitely accept a Pull Request from a contributor who can get this to work, but I have given up on trying to do it myself.

I've added this to the Roadmap to make this clearer.
