### ISSUE TITLE
Will not create a new box (and version inconsistency.)

### ISSUE THREAD

**Issue by Xarius86** [Dvlv/BoxBuddyRS#11]
Running `Fedora Silverblue 39` with `distrobox` layered.

Running `BoxBuddy 1.0.8` according to the in-app dialog, but is actually `1.0.7` according to `flatpak list` and _Flathub_. 

When trying to create the first distrobox when no others exist, the app simply shows a spinning wheel indefinitely. It doesn't crash, it just simply does nothing. 

If there are existing distroboxes, then the app performs as expected.

**Comment by Dvlv** [comment]
I'll investigate if any images are requiring user-input before/after downloading, but my gut instinct is that it's just taking a _long_ time to pull these images. The UI feedback is definitely inadequate, I'd ideally like a mini-scrolling-terminal-output box like Mint's software updater has, but I'll need time to figure out how to do that.

The version thing is just me forgetting to update the AppData file when pushing to the Flathub repo. Automating release management is on my TODO list

**Comment by Dvlv** [comment]
Do you remember which image you were trying to create when it spun indefinitely?

**Comment by Xarius86** [comment]
All of the archlinux images. A couple of the Fedora images (can't remember specifically, but at least one of the 39 versions.) I tried one of the openuse images and also an ubuntu one. I can't remember which ones precisely. Other ones like randomly selecting Fedora 36 worked just fine. 

I do think you are right about it being ones that require user input. I noticed when doing things in the CLI that the first time you download an image, you need to confirm it to continue. There are also times when you are selecting an image that it asks you which of four or five sources you want to use. 

Now I have a bunch of images that are already downloaded, so it's installing just fine without needing to ask which source, or for a confirmation to initially download it, thus no hang in BoxBuddy for those.

**Comment by Dvlv** [comment]
Distrobox _shouldn't_ request any input, as I'm passing `-Y`, but I don't know for sure.
1) What version of distrobox do you have?
2) Are you using NVIDIA?

**Comment by Xarius86** [comment]
1. distrobox: 1.6.0.1
2. No, this is an old laptop with an Intel processor and integrated graphics.

**Comment by Dvlv** [comment]
Think this should be sorted in 1.0.9

Looks like potential issues with the Flathub builder so might be a little bit until the Flatpak updates

**Comment by Xarius86** [comment]
I'll keep an eye out. Thanks!

**Comment by Dvlv** [comment]
Assume this was fixed in 1.0.9. 

I'll close this issue, but if it's still happening for anyone, feel free to re-open or raise a new one.
