### ISSUE TITLE
permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by rahim-gh** [Dvlv/BoxBuddyRS#110]
**Install method (Flatpak/Binary/Other)**
from binary

**Distrobox Version**
`distrobox --version` will tell you this.
distrobox: 1.7.2.1

**Your Host OS**
Fedora 40

**Describe your Issue**
trying to create the first container, choosed the image and click *create*. terminal appears and shows this error message:

```
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.46/containers/test/json": dial unix /var/run/docker.sock: connect: permission denied
Create it now, out of image registry.fedoraproject.org/fedora-toolbox:39? [Y/n]:
```

whether answer yes or no it exit imidiatley and no new container appears

**Comment by Dvlv** [comment]
https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue

Please bear in mind BoxBuddy is just a GUI, so issues with docker are best reported to the Docker project.
