### ISSUE TITLE
Ubuntu 24.04 not showing up in available options?

### ISSUE THREAD

**Issue by erenfro** [Dvlv/BoxBuddyRS#111]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
2.2.8

**Your Host OS**
Linux Mint 22.0beta

**Describe your Issue**
No options are listed for Ubuntu 24.04 including:
docker.io/library/ubuntu:24.04
quay.io/toolbx/ubuntu-toolbox:24.04

**Comment by Dvlv** [comment]
Hello, this list comes from Distrobox, please report this issue upstream.
