### ISSUE TITLE
Broken on Debian 12 / Flatpak version doesn't see Applications inside distrobox

### ISSUE THREAD

**Issue by Xdavius** [Dvlv/BoxBuddyRS#113]
**Install method (Flatpak/Binary/Other)**

Binary and pacscript from source (rustup)

**Distrobox Version**
1.4.2.1-1

**Your Host OS**
Debian 12 Bookworm

**Describe your Issue**

Hi dev,

The binary cannot be executed on Debian 12 (glib >= 2.38 and gtk4 >= 4.10)

https://packages.debian.org/fr/source/bookworm/glibc
https://packages.debian.org/source/bookworm/gtk4

Build from source also fail for gtk4 version requested, too high for Debian.

Tested flatpak version : Doesn't see installed applications insides the boxes to export. (box creation works) [EDIT: Seems ok with distrobox-git)

**Comment by Dvlv** [comment]
Hello

The binary is built on Fedora 39, so I guess Debian is too far behind.

Flatpak of BoxBuddy + Distrobox from Git is probably the best way to support Debian.

**Comment by Xdavius** [comment]
> Hello
> 
> The binary is built on Fedora 39, so I guess Debian is too far behind.
> 
> Flatpak of BoxBuddy + Distrobox from Git is probably the best way to support Debian.

Hi.

In fact, I'm not able to provide boxbuddy from source/binary for Debian 12 on pacstall.

I have provided distrobox-git and latest stable. It's working with flatpak version.

I regret to be blocked to share boxbuddy via pacstall. It's a good app.
