### ISSUE TITLE
Generate systemd-userservices for containers with init

### ISSUE THREAD

**Issue by marissa999** [Dvlv/BoxBuddyRS#115]
- [X] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [X] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [X] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below

Is it potentially possible to have BoxBuddy autogenerate a systemd user service so that a container/distrobox would start automatically when the system started? It might be useful to install a service in a distrobox, and then to have the service start with the system/desktop.

Maybe something like this, but just generated on demand with the press of a button:
https://github.com/89luca89/distrobox/issues/1042#issuecomment-2053887376

**Comment by Dvlv** [comment]
Hello, thanks for the suggestion.
I think this is out of scope for BoxBuddy, as it is just meant to be a UI for the features of distrobox.

If distrobox added a command such as `distrobox create-systemd-service` then I would add a button to BoxBuddy which called this function.
