### ISSUE TITLE
BoxBuddy is displaying zh_CN instead of zh_TW, is this the problem?

### ISSUE THREAD

**Issue by xlionjuan** [Dvlv/BoxBuddyRS#121]
**Install method (Flatpak/Binary/Other)**

Flatpak

**Describe your Issue**
https://github.com/Dvlv/BoxBuddyRS/blob/d406c3962e13a6c41f5a2ce74daf481ac7737726/po/zh_CN/LC_MESSAGES/zh_CN.po#L15

**Comment by xlionjuan** [comment]
It fixed by running binary directly👍️

I thought the original translater is guessing that doing this will let the system that ISO code starting with `zh` can display that translation, because we (zh_TW) can fully understand the words or terms in zh_CN, better than not, but actually, before 2.2.11, BoxBuddy is always displaying English, not zh_CN, haha..

![圖片](https://github.com/user-attachments/assets/cc4500fa-f700-4dd8-97e2-3a8f4daa41ee)

![圖片](https://github.com/user-attachments/assets/f3355266-2604-4f40-8aba-e2bb50532952)

**Comment by Dvlv** [comment]
Nice. 2.2.12 should now be on flathub too
