### ISSUE TITLE
Downloading images doesn't work if no podman/docker is installed

### ISSUE THREAD

**Issue by K0-RR** [Dvlv/BoxBuddyRS#122]
I just installed this app (and distrobox) and it didn't work. It took me a few minutes to understand I also need to install podman or docker. BoxBuddy doesn't mention this.

The issue here is that there will be no info about an error from BoxBuddy, when a user tries to download an image without a container manager.

**Comment by Dvlv** [comment]
Thanks for the report, I will add a message if neither podman or docker can be found.

This will release in 2.2.13
