### ISSUE TITLE
App does not launch from "Installed Applications > Run"

### ISSUE THREAD

**Issue by joshbrooks** [Dvlv/BoxBuddyRS#123]
**Install method (Flatpak/Binary/Other)**

Installed via deb file

**Distrobox Version**

1.2.7.1

**Your Host OS**

Fedora Bluefin

**Describe your Issue**

I installed a gui app Sirikali on an ubuntu distrobox.
It shows up in `Installed Applications`
I can open it from the terminal
I can add it to the menu and open it
But clicking "run" does not open it

Installing another appliation (geany) **does** work

**Comment by VortexAcherontic** [comment]
Hey there, this is not a BoxBuddy issue but distrobox. Please report this to upstream.

About the actual issue:
Take a look at the .desktop file of the exported app. There is probably a line called ExecPath or something similar which points to a directory inside the distrobox which isn't available on the Host. Change it to a directory which is present on the host and try again.
