### ISSUE TITLE
Homebrew install not detected

### ISSUE THREAD

**Issue by MalikKillian** [Dvlv/BoxBuddyRS#125]
**Install method (Flatpak/Binary/Other)** Homebrew

**Distrobox Version** 1.7.2.1

**Your Host OS** Debian Bookworm

With a typical Homebrew installation of distrobox, BoxBuddy is unable to find the installation. It is available on my PATH from a regular terminal but perhaps the GUI only looks in standard locations. After I created a few symbolic links in `/usr/local/bin` for distrobox and podman (also a Homebrew install) BoxBuddy worked as expected.

**Comment by Dvlv** [comment]
Hello
Thanks for the report, but there's nothing BoxBuddy can do about this.

I assume you have homebrew's PATH set up in your shell-specific config (.bashrc or .zshrc etc) but when BoxBuddy launches a subprocess it does not spawn the shell, so you'd need brew's PATH somewhere global.

See https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix
