### ISSUE TITLE
ublue is incorrectly recognized as "arch" distribution

### ISSUE THREAD

**Issue by igor2x** [Dvlv/BoxBuddyRS#126]
**Install method (Flatpak/Binary/Other)**
BoxBuddy 2.2.13 installed as flatpak

**Distrobox Version**
distrobox: 1.7.2.1

**Your Host OS**
Blufin 40 (one of ublue releases that is based on Fedora Silverblue)

**Describe your Issue**
On web page[ distrobox 1.8.0 Release Notes](https://github.com/89luca89/distrobox/releases/tag/1.8.0) there is info: *A lot of new container distros, from ublue-os and...*

I checked with BoxBuddy:
1. Top-left click on "+".
2. Click on drop-down right of Image field.
3. In Search field type in: ublue
and ublue is displayed, but it is prefixed with "arch" which is incorrect. I think it should be prefixed with "ublue".
![image](https://github.com/user-attachments/assets/2d2b953c-4aa3-4689-b160-59382fdc800a)

**Comment by Dvlv** [comment]
Hello, thanks for the report.
I have made some changes to the distro detection and pushed them to master.

I need to update the translation system and move the Flatpak SDK to Gnome 47, so these changes will be released alongside all of that.
