### ISSUE TITLE
unknown title for some Linux distros

### ISSUE THREAD

**Issue by igor2x** [Dvlv/BoxBuddyRS#127]
**Install method (Flatpak/Binary/Other)**
BoxBuddy 2.2.13 installed as flatpak

**Distrobox Version**
distrobox: 1.7.2.1

**Your Host OS**
Blufin 40 (one of ublue releases that is based on Fedora Silverblue)

**Describe your Issue**
1. Top-left click on "+".
2. Click on drop-down right of Image field.
3. In Search field type in: unknown

It is great that distros are at least displayed. But improvement could be made to actually name distros instead of "unknown".

![image](https://github.com/user-attachments/assets/2b7af9e6-1f43-4f49-83e5-184b0eecc6b3)

**Comment by Dvlv** [comment]
Hello
Yes, when BoxBuddy cannot determine what distro an image is, it will show Unknown. This is intentional.

**Comment by igor2x** [comment]
I see you have updated BoxBuddy in flatpak. That is great. Thanks.

There are still two unknown Linux distributions:
![image](https://github.com/user-attachments/assets/2e476a1c-7b0f-431c-b2bd-6f959b4a4d3d)

Unknown:
- first on the list is [Wolfi OS](https://github.com/wolfi-dev)
- second on the list is [Scientific Linux](https://scientificlinux.org/downloads/sl-versions/sl7/)
