### ISSUE TITLE
elementary terminal is not recognized

### ISSUE THREAD

**Issue by diogopessoa** [Dvlv/BoxBuddyRS#130]
**Install method (Flatpak)**
BoxBuddy flatpak

**Distrobox Version**
Distrobox 1.8.0

**elementary OS 8**
OS 7 also had the same issue.  

**Describe your Issue**
In BoxBuddy there is no option to select the elementary terminal (io.elementary.terminal) as default.
https://github.com/elementary/terminal

**Comment by Dvlv** [comment]
Hello,
Thanks for the report, this will be added in the next release.
