### ISSUE TITLE
preferred terminal set to ptyxis, but still launches gnome-terminal instead

### ISSUE THREAD

**Issue by killarny** [Dvlv/BoxBuddyRS#131]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
distrobox: 1.7.0

**Your Host OS**
Ubuntu 24.10

**Describe your Issue**
Using BoxBuddy 2.3.1, I've set my preferred terminal to ptyxis. However, clicking "Open Terminal" on a container opens gnome-terminal instead.

*Note: I've installed both BoxBuddy and Ptyxis via flatpak.*

![image](https://github.com/user-attachments/assets/be489d91-1ba2-49f2-9844-ffe27850a2f0)

**Comment by Dvlv** [comment]
Hello

https://www.dvlv.co.uk/BoxBuddyRS/faqs#my-preferred-terminal-is-a-flatpak-why-cant-boxbuddy-open-it

**Comment by killarny** [comment]
Ahh okay, thanks for pointing me there! Sorry, I missed that item in the FAQ.

> BoxBuddy is not programmed to be able to launch Flatpaks.
>
> You can get around this by making a wrapper script

The wording there kinda makes it sound like it's a feature that hasn't happened yet, and doesn't make it necessarily clear that it's intended never to be able to do so. If that is your intent (which is totally fair!) then it might be worth clarifying at some point.

Thanks for the nice app!
