### ISSUE TITLE
elementary Terminal instead of Elementary Terminal

### ISSUE THREAD

**Issue by diogopessoa** [Dvlv/BoxBuddyRS#132]
https://github.com/Dvlv/BoxBuddyRS/blob/5b8e3341bec956943889936216477ff5afe13c1a/src/utils.rs#L288

I know it's a stupid suggestion and doesn't affect anything in how it works, but if you want to consider a change, the name "elementary OS" is the same, whether it's at the beginning of the sentence or not.

I am an elementary and Buddy user. 
Thank you for your work!

**Comment by Dvlv** [comment]
Thanks, I've changed that.
