### ISSUE TITLE
Cannot pick up Ptyxis Terminal from Flathub with wrapper script

### ISSUE THREAD

**Issue by heldderarbeit** [Dvlv/BoxBuddyRS#134]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
1.8.0

**Your Host OS**
Arch

**Describe your Issue**

Hello, I'm trying to get BoxBuddy 2.3.2 to recognize Ptyxis Terminal 47.4. Both are from Flathub, so I tried to follow the instructions with the wrapper script from the section "[My preferred terminal is a Flatpak, why can’t BoxBuddy open it?](https://www.dvlv.co.uk/BoxBuddyRS/faqs#my-preferred-terminal-is-a-flatpak-why-cant-boxbuddy-open-it)".

I must be missing something, because I can't get Boxbuddy to pick up Ptyxis, even with the wrapper. I get the "No supported terminal found - Please install one of the supported terminals" window popup, no matter what I try. My setup:

`cat ~/.local/bin/ptyxis` (renaming to Ptyxis doesn't work either):

```
#!/usr/bin/env fish
flatpak run app.devsuite.Ptyxis $argv
```

`ls -l ~/.local/bin/ptyxis`:
`-rwxr-xr-x`

`echo $PATH`:
`/home/xxx/.local/bin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl`

`cat ~/.local/share/flatpak/overrides/io.github.dvlv.boxbuddyrs`: 
```
[Context]
filesystems=~/.local/bin;home;host-etc;host-os;host
```

podman 5.2.5 and crun 1.18.2 are installed.

I think I followed all the instructions, but it's still not working. What am I missing?

**Comment by Dvlv** [comment]
Hello
Is your wrapper script definitely available globally? If you only adjusted your PATH in your fish config it wont be picked up, as BoxBuddy won't spawn your shell.

https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix

**Comment by heldderarbeit** [comment]
Thanks for the help!
I noticed I just had to restart (I added the path with `fish_add_path`) and now it just works 'like that'!  🫣 I clearly shouldn't do those things at 6 o'clock in the morning…

Sorry for the noise!
