### ISSUE TITLE
Terminator Terminal Support

### ISSUE THREAD

**Issue by agleeson38930** [Dvlv/BoxBuddyRS#138]
- [ ] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [ ] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [ ] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
It states in the FAQ to drop an issue for a request for a terminal support. Would it be feasible to add Terminator to this list?

Thanks

**Comment by Dvlv** [comment]
Hello
thanks for the suggestion, I have added Terminator support, and pushed to master.
