### ISSUE TITLE
Name of application is not sanitized

### ISSUE THREAD

**Issue by Ferenc-** [Dvlv/BoxBuddyRS#14]
In debian based distros there is a GUI tool called `Software&Updates` also known as [software-properties-gtk](https://packages.debian.org/bullseye/software-properties-gtk), which doesn't get listed by `BoxBuddy` when one clicks `ViewApplications`. Instead the warning below gets logged:

````
(boxbuddy-rs:2): Gtk-WARNING **: 09:40:38.457: Failed to set text 'Software&Updates' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
````

**Comment by Dvlv** [comment]
Thanks for the bug report, this should be sorted in 1.0.10, which is making its way to flathub now.
