### ISSUE TITLE
Cloning Fedora container uses ublue-os/ubuntu-toolbox instead

### ISSUE THREAD

**Issue by ikidd** [Dvlv/BoxBuddyRS#140]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
v1.8.0

**Your Host OS**
Aurora-DX

**Describe your Issue**

Cloning a working fedora40 container:

```
Error: no such container KtailCtl
Creating the container KtailCtl
Trying to pull ghcr.io/ublue-os/ubuntu-toolbox:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob 3341066a79f6 skipped: already exists  
Copying blob 7daed09b85d5 skipped: already exists  
Copying config 136723b0e6 done   | 
Writing manifest to image destination
Storing signatures
136723b0e699bd231c2051c2e25c4949705a685b8c91876757003353a46dace8
Creating 'KtailCtl' using image ghcr.io/ublue-os/ubuntu-toolbox:latest	 [ OK ]
Distrobox 'KtailCtl' successfully created.
```
Now I have a ubuntu install and if I close and reopen BoxBuddy, the list of applications has changed from VSCode and some QT helpers to ImageMagick, fish, Texinfo and Vim, none of which work.

I really have no idea what this is doing, and I've tried it multiple times.

**Comment by Dvlv** [comment]
Hello

Cloning is done via `distrobox create --clone` so I'd suggest filing this issue upstream.

> Error: no such container KtailCtl
> Creating the container KtailCtl

Is KtailCtl the name of the box you are trying to create? If so, it looks like the create is not working. I'd suggest trying

 ```
distrobox create --clone box_to_clone --name new_box_name
```

via the CLI and see if you get an error
