### ISSUE TITLE
distrobox-export --list-binaries

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [Dvlv/BoxBuddyRS#146]
- [X] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [X] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [X] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
BoxBuddyRS can already list exported GUI-apps (I think? I don't do GUI apps from podman...), which is lovely. But it refuses to list exported binaries [cli: `distrobox-export --list-binaries`]. Could this be added?

**Comment by Dvlv** [comment]
Hello,
Thanks for the suggestion.
I've not got a whole lot of free time (or motivation) to work on this now, but I think it would be a nice feature.

**Comment by Dvlv** [comment]
Pushed to master
