### ISSUE TITLE
[Feature Request] --nvidia option at creating a new container

### ISSUE THREAD

**Issue by VortexAcherontic** [Dvlv/BoxBuddyRS#17]
When creating a new distrobox container an option to allow for integrating the host nvidia driver is missing.

distrobox-create --name mybox --nvidia

**Comment by Dvlv** [comment]
This is applied automatically if NVIDIA is detected by `lspci`.

https://github.com/Dvlv/BoxBuddyRS/blob/4ffdfe2d5036538378050dd741531914c905a67b/src/distrobox_handler.rs#L236
