### ISSUE TITLE
Add NVIDIA GPU acceleration support automatically

### ISSUE THREAD

**Issue by henriquead7** [Dvlv/BoxBuddyRS#3]
Hello, congratulations on the app, are there plans to automatically add the "`--nvidia`" flag that enables the use of graphic acceleration of gpus nvidia with the same driver host in the container?

BoxBuddy did not identify my GPU Nvidia and applied the flag, so I created the container manually, for example:

`distrobox create --image fedora:39 --name fedora-nvidia --nvidia
`

Then everything went normally on BoxBuddy.

**Comment by Dvlv** [comment]
Hi, yes I was planning on making the Nvidia switch a checkbox on the create box page, though I suppose detecting the hardware and passing it transparently is probably better UX.

I'll update this issue when I release 1.0.5

**Comment by Dvlv** [comment]
Released in v1.0.6
