### ISSUE TITLE
Can't see the custom home directory option

### ISSUE THREAD

**Issue by nobodywatchin** [Dvlv/BoxBuddyRS#34]
When I create a new box, I am not seeing the custom home directory as an option. 
Is there something I am missing?
![Screenshot from 2024-01-29 23-20-53](https://github.com/Dvlv/BoxBuddyRS/assets/118339799/f45eb33f-c0be-4683-8431-ef13cf665d5b)
![Screenshot from 2024-01-29 23-20-41](https://github.com/Dvlv/BoxBuddyRS/assets/118339799/d36a5dcc-d867-4bca-8df8-17740f100524)

**Comment by Dvlv** [comment]
Assuming this is the flatpak version, you need to grant BoxBuddy access to either `home` or `host`.

Docs: https://dvlv.github.io/BoxBuddyRS/tips

**Comment by CorneliusCornbread** [comment]
This still seems to be an issue even after enabling Home directory access via flatseal
![image](https://github.com/user-attachments/assets/1632c54b-41e5-4aba-a4c0-fc90e4164de6)
![image](https://github.com/user-attachments/assets/6e2f0a20-98fa-4485-b5dc-c768d826b0f0)

**Comment by Dvlv** [comment]
Home access detection must have been broken by granting it by default.

Need to update the function to parse this:

```
> flatpak info -M io.github.dvlv.boxbuddyrs
[Context]
shared=ipc;
sockets=x11;wayland;fallback-x11;
devices=dri;
filesystems=home;host;

[Session Bus Policy]
org.freedesktop.Flatpak=talk
```
