### ISSUE TITLE
no boxes on nixos

### ISSUE THREAD

**Issue by RAVENz46** [Dvlv/BoxBuddyRS#35]
**Install method (Flatpak/Binary/Other)**
Flatpak and my own derivation
<details>

<summary>Here is my derivation</summary>

```
{ lib
, rustPlatform
, fetchFromGitHub
, pkg-config
, wrapGAppsHook4
, cairo
, gdk-pixbuf
, glib
, gtk4
, libadwaita
, pango
}:

rustPlatform.buildRustPackage rec {
  pname = "box-buddy-rs";
  version = "1.2.0";
  name = "${pname}-${version}";

  src = fetchFromGitHub {
    owner = "Dvlv";
    repo = "BoxBuddyRS";
    rev = version;
    hash = "sha256-sKkUUDKtRISDV1B3aPN8Q5vj2fmmffjEEfORmpH0ZpY=";
  };

  cargoHash = "sha256-XIGtYoKipxTZ9mIZfX2us9qBPiI136kPGlM8wN/eWUA=";

  nativeBuildInputs = [
    pkg-config
    wrapGAppsHook4
  ];

  buildInputs = [
    cairo
    gdk-pixbuf
    glib
    gtk4
    libadwaita
    pango
  ];

  preBuild = ''
    mkdir -p $out/share/applications

    install -m 444 \
        -D $src/io.github.dvlv.boxbuddyrs.desktop \
        -t $out/share/applications
    cp -r $src/icons $out/share
  '';

  meta = with lib; {
    description = "A Graphical Interface for Distrobox";
    homepage = "https://github.com/Dvlv/BoxBuddyRS";
    license = licenses.mit;
    maintainers = with maintainers; [ ];
    mainProgram = "box-buddy-rs";
  };
}
```

</details>

**Distrobox Version**
`distrobox --version` will tell you this.
```
$ distrobox --version
distrobox: 1.5.0.2
```
boxbuddy == v1.2.0

**Describe your Issue**
Even though I already running distrobox containers, it says no boxes.

[info]
OS: NixOS 24.05 (Uakari) x86_64
Kernel: Linux 6.1.74

I set there enviromental variables:
DBX_CONTAINER_HOME_PREFIX = "/home/ravenz46/dbx";
DBX_CONTAINER_MANAGER = "podman";
DBX_SKIP_WORKDIR = "1";

**Comment by Dvlv** [comment]
Hello,
Sorry but I don't know the first thing about NixOS, you'll probably have more luck getting support from somewhere nix-specific.

**Comment by idoodler** [comment]
Did you do anything specific? I am on SteamOS, I have the issue that BoxBuddy doesn't see boxes created using distrobox CLI and vice versa. I installed BoxBuddy from the discovery Application using Version 2.3.0.
