### ISSUE TITLE
Few features request

### ISSUE THREAD

**Issue by ozky84** [Dvlv/BoxBuddyRS#37]
1.stop distrobox instance
2.custom values to start distrobox
`https://distrobox.it/useful_tips/#using-init-system-inside-a-distrobox`
4. is there really point why not bundle distrobox in Boxbuddy as it needs lots of permissions use distrobox outside of flatpak?

**Comment by Dvlv** [comment]
Hello
1. Already in 1.2.0
2. Already in 1.2.0

4. As far as I know Podman needs to be on the host - no other Podman GUI I know of repackages it.
