### ISSUE TITLE
the created containers don't have so much as the needed kernal for that distro, and other issues after fixing

### ISSUE THREAD

**Issue by Nathan22211** [Dvlv/BoxBuddyRS#4]
I've been trying to make a Ubuntu distrobox to run iriun webcam's Linux driver in, but upon attempting, it become quickly clear that not even the proper kernel is included in the distrobox. I'm on Garuda Linux, which uses the linux-zen kernel and even after having it fix broken packages, it still tries to find the needed libraries under the host kernel.

**Comment by Dvlv** [comment]
Hello, this seems like an issue with Distrobox itself. BoxBuddy is just a UI.
Please open an issue on Distrobox's tracker https://github.com/89luca89/distrobox/issues
