### ISSUE TITLE
Logo suggestion

### ISSUE THREAD

**Issue by VortexAcherontic** [Dvlv/BoxBuddyRS#41]
As I looked up the roadmap I saw the entry of "nicer Logo" as I don't know what you're aiming for I just throw up a random idea:

![io github dvlv boxbuddyrs](https://github.com/Dvlv/BoxBuddyRS/assets/11244092/198736de-0a49-4701-9f8d-31b4f6f2cb74)

I think it's probably the most cutest box I've ever seen but not sure if you're aiming for a more symbolic or a more industrial design or what ever. So it's just a shot in the dark here.

If you want to look at the svg you can do so in [design branch](https://github.com/VortexAcherontic/BoxBuddyRS/blob/design/icons/logog_design.svg)

**Comment by Dvlv** [comment]
That is very cute, but I was thinking of something more in-line with the GNOME HIG

https://developer.gnome.org/hig/guidelines/app-icons.html

**Comment by VortexAcherontic** [comment]
Not sure if these are any closer you decide 😄 

![box_v2](https://github.com/Dvlv/BoxBuddyRS/assets/11244092/45a64bf4-d61c-4313-9c58-5d65740ffb67)

![box_v3](https://github.com/Dvlv/BoxBuddyRS/assets/11244092/98c982c4-cd36-460b-9d28-d3348573d88b)

**Comment by Dvlv** [comment]
![logo-recoloured](https://github.com/Dvlv/BoxBuddyRS/assets/4907493/833dfd98-6d28-473d-9678-9877241a7650)

I've changed the proportions to the GNOME template and changed the colour scheme to their pallette. What do you think?

**Comment by VortexAcherontic** [comment]
This looks incredibly good!

**Comment by Dvlv** [comment]
Awesome, gonna make this the new logo then, thank you!
