### ISSUE TITLE
Can't create box

### ISSUE THREAD

**Issue by TDYQ-Liu** [Dvlv/BoxBuddyRS#43]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
`distrobox --version` will tell you this.
distrobox: 1.6.0.1

**Your Host OS**
fedora 39

**Describe your Issue**
- start boxBuddyRS
- click '+'
- no response

`flatpak run io.github.dvlv.boxbuddyrs` I tried cli running but there is no log

![Screenshot from 2024-02-04 20-16-29](https://github.com/Dvlv/BoxBuddyRS/assets/71477981/9cfff6d1-7949-4804-b6cf-5f82d11a687e)
![Screenshot from 2024-02-04 20-16-43](https://github.com/Dvlv/BoxBuddyRS/assets/71477981/b76291f3-5d7a-4c43-b9a6-692d5d599a43)
![Screenshot from 2024-02-04 20-16-53](https://github.com/Dvlv/BoxBuddyRS/assets/71477981/946ea159-ebd9-4f78-aa97-f624ad26d722)

**Comment by Dvlv** [comment]
Hmm, this is strange, I'm using fedora 39 to develop this. 

- Have you made any changes in Flatseal?
- Is BoxBuddy installed as a user or system flatpak? `flatpak list --columns=app,installation | grep boxbuddyrs`

**Comment by TDYQ-Liu** [comment]
> Hmm, this is strange, I'm using fedora 39 to develop this.
> 
> * Have you made any changes in Flatseal?
> * Is BoxBuddy installed as a user or system flatpak? `flatpak list --columns=app,installation | grep boxbuddyrs`

Flatseal conf is default.
I installed as system. I didn't add the --user option when install and the location is in /var/lib/flatpak

Since I am in UTC+8 time zone(10:35PM), I will reply to you tomorrow

**Comment by Dvlv** [comment]
I've spun up a fresh f39 VM and installed boxBuddy as system and it's all working. I even took myself out of the wheel group and it still works. 

If you run `flatpak override --show io.github.dvlv.boxbuddyrs` does it ask you for your sudo password?

**Comment by TDYQ-Liu** [comment]
> I've spun up a fresh f39 VM and installed boxBuddy as system and it's all working. I even took myself out of the wheel group and it still works.
> 
> If you run `flatpak override --show io.github.dvlv.boxbuddyrs` does it ask you for your sudo password?
> 
> Also what is your system Locale?

Today I turned on my computer and found that it can be used normally. 🤔
![Screenshot from 2024-02-05 09-35-12](https://github.com/Dvlv/BoxBuddyRS/assets/71477981/0089e016-ce79-4cd6-9cae-e9b27a995686)

```sh
$ flatpak list --columns=app,installation | grep boxbuddyrs
io.github.dvlv.boxbuddyrs	system
```

```sh
flatpak override --show io.github.dvlv.boxbuddyrs
# doesn't ask my password
```

```sh
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by TDYQ-Liu** [comment]
In addition, it seems that there is no problem from the log.

![Screenshot from 2024-02-05 09-40-40](https://github.com/Dvlv/BoxBuddyRS/assets/71477981/4b31575b-5ab5-45e8-a551-a623a032258e)

**Comment by Dvlv** [comment]
Glad it's working for you now! :)
