### ISSUE TITLE
Fails to "find" pre-existing distroboxen.

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [Dvlv/BoxBuddyRS#5]
See title.

Tools like Podman Desktop and Cockpit do find my distroxen but this tool does not.

**Comment by Dvlv** [comment]
Are they rootful boxes? BoxBuddy won't see rootful boxes unless you run it as root.
Otherwise, I'll need more details.

**Comment by ParaplegicRacehorse** [comment]
Okay, so a little bit weird. My distroboxen don't appear with `list` but podman desktop finds them just fine.

```
suzette@tux-suzette:~$ distrobox --version
distrobox: 1.5.0.2
suzette@tux-suzette:~$ distrobox list
ID           | NAME                 | STATUS             | MEM              | CPU%  | IMAGE                         
Error: container state improper
suzette@tux-suzette:~$ distrobox list --root
ID           | NAME                 | STATUS             | MEM              | CPU%  | IMAGE                         
suzette@tux-suzette:~$ podman ps
CONTAINER ID  IMAGE                                      COMMAND               CREATED      STATUS          PORTS       NAMES
7325403cce33  quay.io/toolbx-images/alpine-toolbox:edge  --verbose --name ...  4 weeks ago  Up 2 hours ago              cli-apps
```

I see a container state improper note but, of course, there's no suggestion on how to troubleshoot that. So, it seems my issue may be with my distrobox install and not your GUI.

===

And, a restart of BoxBuddy finds the distroboxen just fine.  Weird.

So, now this comment is just general feedback and what seems to be working correctly, what could be improved, etc. (Note: my setup: TuxedoOS [Ubuntu LTS 22.04 base], bash, KDE Plasma, BoxBuddy installed as flatpak]

- Creation of new box does not show an indication of already-downloaded images. I have, on-device, images of fedora:39, alpine-toolbox:edge, opensuse-toolbox:latest. These do not appear at top of list and there is not checkmark or other visual indicator that I already pulled these from the registry.
  - It's super sweet that it finds all registries in my registry conf.
  - Kind of a bummer that it doesn't offer an option to pull from a custom registry not in registries conf.
  - After creation of a new db, list of available boxen does not auto-refresh and the application requires a restart to find.
- View Applications does not find all applications installed inside the box. Does it only look for exported bins/apps?
- Enhancement requests:
  - Export and un(?)-export apps/bins installed in the box.
  - Start/stop boxen.
  - When creating new box, visual indication of which images are already on-device.

Anyway, thanks for the quick response. My issue seems to have resolved itself.
