### ISSUE TITLE
Application list is not scrollable

### ISSUE THREAD

**Issue by LucasGGamerM** [Dvlv/BoxBuddyRS#58]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Your Host OS**
Pop!_OS

**Describe your Issue**
The application list dialog menu is not scrollable, making it extremely hard to go through the application list.

I have a bunch of audio tools installed, which made the application list balloon to an enormous size. This makes it impossible to navigate my applications, which is really frustrating

**Comment by Dvlv** [comment]
Thanks for the suggestion, fix coming up in 2.1.1

**Comment by Dvlv** [comment]
2.1.1 is now available
