### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Vovkiv** [Dvlv/BoxBuddyRS#6]
Support for adding translations maybe?

**Comment by Dvlv** [comment]
Hello.
That would be great, but I only know English myself, so somebody will have to provide translations for me.
If anyone is interested in doing this, please open a PR

**Comment by Vovkiv** [comment]
Well, by "Localization support" I mean you need to provide translation system. Usually with GTK software this is gettext. Take look at Resources: https://github.com/nokyan/resources, which is also Rust program.

**Comment by Dvlv** [comment]
Ah, I see, thank you for the example.
I will have a look into `gettextrs` and update this issue.

**Comment by Dvlv** [comment]
Localisation support should be ready in master now.

**Comment by Vovkiv** [comment]
Yay!
I will try add some localizations and see how it will go.

**Comment by Dvlv** [comment]
Oh, FYI for development you will need to edit `src/utils.rs` and comment out lines 181 - 188, so the `locale_directory` is `"./po"`
