### ISSUE TITLE
feature request: add support for WezTerm

### ISSUE THREAD

**Issue by swaits** [Dvlv/BoxBuddyRS#65]
**Install method (Flatpak/Binary/Other)**: Flatpak

**Distrobox Version**: 1.6.0.1

**Your Host OS**: Fedora Budgie Atomic

**Describe your Issue**

_Per FAQ, filing this issue for an unsupported terminal:_

I'd like to add WezTerm to the list of supported terminal programs. I run WezTerm as a Flatpak, but I suspect many others have it installed through their normal package manager (command: `wezterm`). I hope you can support both methods of launching it. Thanks!

**WezTerm References:**

Flathub: https://flathub.org/apps/org.wezfurlong.wezterm
Home Page: https://wezfurlong.org/wezterm/
Github: https://github.com/wez/wezterm

**Comment by Dvlv** [comment]
Thanks for the suggestion, this will be released in 2.1.3.

BoxBuddy cannot spawn Flatpaks, but I've added some documentation on how to work around that:

https://dvlv.github.io/BoxBuddyRS/faqs#my-preferred-terminal-is-a-flatpak-why-cant-boxbuddy-open-it

**Comment by Dvlv** [comment]
2.1.3 released, just making its way through Flathub now
