### ISSUE TITLE
unable to shrink the window height

### ISSUE THREAD

**Issue by dnkmmr69420** [Dvlv/BoxBuddyRS#66]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
`distrobox --version` will tell you this.
distrobox: 1.6.0.1

**Your Host OS**
ublue bazzite 39 with kde wayland

**Describe your Issue**
I can't shrink the window height. There should be a scroll bar so I can resize the height of the window so it fits my screen.

**Comment by Dvlv** [comment]
Thanks for the suggestion, this will be released in version 2.1.3

**Comment by Dvlv** [comment]
2.1.3 released, just making its way through Flathub now
