### ISSUE TITLE
Expanding es_ES locales

### ISSUE THREAD

**Issue by sebrice** [Dvlv/BoxBuddyRS#70]
I wonder if it is possible to apply the es_ES locale to all of es_XX so it works for all the Spanish dialects. The current es_ES translation works perfectly for all of them. I would gladly do it but i do not have the expertise. Including all of the es_XX locales one by one is a solution but it seems convoluted as there are many different es_XX locales.

**Comment by Dvlv** [comment]
Hello,
This should just be a simple loop as part of the build scripts.

Are the current es_ES translations valid for all of these locales?

- es_AR
- es_BO
- es_CL
- es_CO
- es_CR
- es_CU
- es_DO
- es_EC
- es_ES
- es_GT
- es_HN
- es_MX
- es_NI
- es_PA
- es_PE
- es_PR
- es_PY
- es_SV
- es_US
- es_UY
- es_VE

**Comment by Dvlv** [comment]
Looks like I can just rename it to `es` and it will apply to them all.

**Comment by sebrice** [comment]
> Hello,
> This should just be a simple loop as part of the build scripts.
> 
> Are the current es_ES translations valid for all of these locales?
> 
> - es_AR
> - es_BO
> - es_CL
> - es_CO
> - es_CR
> - es_CU
> - es_DO
> - es_EC
> - es_ES
> - es_GT
> - es_HN
> - es_MX
> - es_NI
> - es_PA
> - es_PE
> - es_PR
> - es_PY
> - es_SV
> - es_US
> - es_UY
> - es_VE
> 

Yes, es_ES are valid for all Spanish variants.

**Comment by Dvlv** [comment]
Released with 2.1.4
