### ISSUE TITLE
Generic Wayland Icon on Exported Apps

### ISSUE THREAD

**Issue by bshor** [Dvlv/BoxBuddyRS#74]
**Install method (Flatpak/Binary/Other)**

BoxBuddy is part of the distro image.

**Distrobox Version**

1.7.0.1

**Your Host OS**

Bazzite, an immutable Fedora 39 Kinoite (KDE) distro.

**Describe your Issue**

I installed two applications in a Fedora 39 container using dnf, Krusader and TexWorks. Then I exported the apps to the host menu using BoxBuddy. Both of them work, but the dock and titlebar icons are the generic "Wayland" icons.

![image](https://github.com/Dvlv/BoxBuddyRS/assets/468070/9ed1705c-a6cb-477a-8183-fe63b0382af0)

**Comment by VortexAcherontic** [comment]
Probably a Distrobox issue as BoxBuddy does instructs distrobox to do it.

Does manually exporting the apps give you icons?

```
distrobox enter your-box
distrobox-export -a app-name
```

**Comment by Dvlv** [comment]
Hello, I suggest filing this issue upstream with Distrobox: https://github.com/89luca89/distrobox/issues
I would recommend you try a reboot or log-out first, as that usually fixes icon issues with Plasma for me.
