### ISSUE TITLE
No Italian language available.

### ISSUE THREAD

**Issue by albanobattistella** [Dvlv/BoxBuddyRS#75]
**Install method :Flatpak**

**Distrobox Version** last version

**Your Host OS: Zorin Os**

Hi,
Italian language in not available.
Could you please test it?
Thanks.
A.

**Comment by Dvlv** [comment]
![boxbuddy-italian](https://github.com/Dvlv/BoxBuddyRS/assets/4907493/98876975-1d5a-43e4-ae52-dc8a0ac87a2c)

Hello, I've spun up a fresh Fedora39 VM, set to Italian at install time, and it appears to be translated.
I'm not sure why it doesn't always translate when you swap the system language, and I don't know if that's BoxBuddy's fault or the system's.
