### ISSUE TITLE
Stats display a bit glitchy

### ISSUE THREAD

**Issue by VortexAcherontic** [Dvlv/BoxBuddyRS#82]
**Install method (Flatpak/Binary/Other)**
- Flatpak
- BoxBuddy: 2.2.1

**Distrobox Version**
distrobox version: 1.7.1.0

**Your Host OS**
openSUSE Aeon

**Describe your Issue**
There is a little long line below the stats of a container:

![grafik](https://github.com/Dvlv/BoxBuddyRS/assets/11244092/d0c60a00-93a7-4d3e-bff7-a2bd0ae6d749)

I just noticed it and did not made any further investigations as of now. Probably just some config missing on my end I assume?

After some investigation I found that the message appears also using podman stats but disappears after a short while. Hitting refresh in the UI however does still give the message shown.

**Comment by Dvlv** [comment]
I dont ever get this on Fedora :thinking: 

Do you see this if you do:

```
podman stats box_name --no-stream --format '{{.CPUPerc}};{{.MemPerc}};{{.MemUsage}}' 2> /dev/null
```

**Comment by Dvlv** [comment]
Pushing something in 2.2.2 which will hopefully sort this.
I was able to recreate it on a Tumbleweed VM, but only with the flatpak

**Comment by VortexAcherontic** [comment]
> Pushing something in 2.2.2 which will hopefully sort this. I was able to recreate it on a Tumbleweed VM, but only with the flatpak

Ay I see. Yeah was about to answer that the command you posted does output no such messages. Many thanks for looking into it :heart:
