### ISSUE TITLE
[FEATURE] Host Nvidia driver integration checkbox

### ISSUE THREAD

**Issue by slimhk45** [Dvlv/BoxBuddyRS#85]
`distrobox create` has an `--nvidia` option to integrate host's nVidia drivers in the guest. This is very important for running GUI apps from Distrobox.

Adding a checkbox to activate this option would be very useful.

**Comment by Dvlv** [comment]
Hello, this is added automatically when NVIDIA hardware is detected.

**Comment by slimhk45** [comment]
Thanks, I didn't know that.

**Comment by slimhk45** [comment]
@Dvlv You should mention it in the documentation for other users.
