### ISSUE TITLE
Ubuntu box terminal doesn't take keystroke input

### ISSUE THREAD

**Issue by MLSci** [Dvlv/BoxBuddyRS#87]
**Install method (Flatpak/Binary/Other)**
Flatpak

**Distrobox Version**
1.7.1.0

**Your Host OS**
Fedora Kinoite 40

**Describe your Issue**
STR:
1. Create a ubuntu box
2. Open its terminal
3. Start typing, notice the cursor is not moving, the terminal is not accepting any letter.
4. Not all keys are affected. A few keys still work, such as backspace, tab, and the four direction arrows. And you can use mouse to paste texts into it.
5. Other distroboxes seem fine - I tested a Fedora box, and a bluefin-cli box.

**Comment by Dvlv** [comment]
Hello, problems with created boxes need to be logged against Distrobox itself.
