### ISSUE TITLE
Remember last selecton from Image drop-down menu

### ISSUE THREAD

**Issue by igor2x** [Dvlv/BoxBuddyRS#89]
I use BoxBuddy v2.2.3 from flatpak.

1. Click on "+" to create new box.
2. Dialog appears. I always create `ubuntu-docker.io/library/ubuntu:22.04` image. My suggestion is, when dialog is displayed in Image drop-down menu automatically select last used image from previous create box action. In my case, I use only one image, I would spare some time, because only Create button would be required to click.

**Comment by Dvlv** [comment]
Hello, thank you for the suggestion.

I would prefer the form to reset its state each time. The widgets are created from anew every time anyway, so saving the state would not be super simple.
