### ISSUE TITLE
Question: how to bind mount?

### ISSUE THREAD

**Issue by MLSci** [Dvlv/BoxBuddyRS#91]
- [ ] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [ ] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [ ] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below
Does BoxBuddy support configuring NFS mount inside the distrobox? My use case is to add network mounted folders to Plex Media Server. So far I'm able to mount that folder to my host. But how to mount it in the distrobox? The reason for it is Plex is installed in the distrobox, not on the host. Currently Plex is unable to see mounted NFS folder.

I also tried looking for `my_distrobox.nspawn`, but couldn't find any `.nspawn` file.

And I don't see any `boxbuddy@my_distrobox.service` either. Or am I supposed to .. ?

Thank you

Cross posted https://github.com/89luca89/distrobox/discussions/1394

**Comment by Dvlv** [comment]
Mounting volumes is done at the point of creating a new box. If you are using the flatpak, you will need to enable Host access.
https://dvlv.github.io/BoxBuddyRS/guide

As for NFS specifically, it sounds like that's a question for Distrobox.
