### ISSUE TITLE
Add bluefin-cli image

### ISSUE THREAD

**Issue by slimhk45** [Dvlv/BoxBuddyRS#93]
The container for bluefin-cli is missing in the drop-down menu to select an image:

ghcr.io/ublue-os/bluefin-cli

It is an image stripped down from useless dependencies for an optimized container workflow on Bluefin. It is using Brew for a unified experience across the Unix desktop (Bluefin, MacOS) and having access to a maximum number of well-tested CLI application packages.

**Comment by Dvlv** [comment]
Hello, these images come from `distrobox create -C`, please log this request upstream https://github.com/89luca89/distrobox/issues
