### ISSUE TITLE
Wrong hostname with Debian on Fedora host

### ISSUE THREAD

**Issue by slimhk45** [Dvlv/BoxBuddyRS#94]
I installed the last version of BoxBuddy from FlatHub.

My host is Bluefin (a battery-included Fedora Silverblue distribution).

When I create a Debian box with BoxBuddy, I always get the wrong hostname. I tried to create the Debian box manually to check if it is a Distrobox problem:

```
distrobox create --image quay.io/toolbx-images/debian-toolbox:latest --name debian --home Distroboxes/Debian/ --nvidia

distrobox enter debian
```

and it also returned the wrong hostname `user@fedora` instead of `user@debian`.

To solve this problem I need to avoid using BoxBuddy for Debian boxes creation on my Bluefin and use this command that enforces the hostname I want:

`distrobox create --image quay.io/toolbx-images/debian-toolbox:latest --name debian --hostname debian --home Distroboxes/Debian/ --nvidia`

Is it possible for BoxBuddy to enforce the hostname automatically (using the name variable of the box) for Debian boxes on Fedora Silverblue hosts like Bluefin?

**Comment by Dvlv** [comment]
Hello, problems with created boxes need to be logged upstream with Distrobox.
