### ISSUE TITLE
Add blackbox-terminal support

### ISSUE THREAD

**Issue by askpng** [Dvlv/BoxBuddyRS#99]
- [x] I have read the FAQs (https://dvlv.github.io/BoxBuddyRS/faqs)
- [x] My feature is not on the Roadmap (https://dvlv.github.io/BoxBuddyRS/ROADMAP)
- [x] I have searched for previous issues (https://github.com/Dvlv/BoxBuddyRS/issues?q=is%3Aissue+is%3Aclosed)

## Describe your feature request below

Hi! I'd like to request support for [Black Box terminal](https://gitlab.gnome.org/raggesilver/blackbox), the [Fedora repo](https://packages.fedoraproject.org/pkgs/blackbox-terminal/blackbox-terminal/) provides as well as [AUR](https://aur.archlinux.org/packages/blackbox-terminal) for example both provide it for native installation.

Thank you!

**Comment by Dvlv** [comment]
Hello,
from some testing with the Fedora package, it doesn't look like Blackbox will integrate properly with BoxBuddy.

Most terminals want to be launched with commands using separate args, e.g.

```
gnome-terminal -- distrobox enter OpenSUSE
```

However, this does not work for Blackbox, it instead wants the command as one argument

```
blackkbox-terminal -c 'distrobox enter OpenSUSE'
```

Unless there's another flag to use, or the maintainer wants to change the argument passing logic, this won't work with BoxBuddy.

**Comment by askpng** [comment]
Got it. Thanks for the quick response and for looking into it, have a great day!
